Add unit tests for io.restassured.RestAssured and io.restassured.specification.Argument
Diffblue-benchmarks/rest-assured pull request #1
Opened 2018-11-27 09:57 UTC by petersear

Hi,
I've analysed your codebase and added some unit tests for the following classes:
    io.restassured.RestAssured
    io.restassured.specification.Argument
I've written the tests for these functions with the help of Diffblue Cover.
These tests should help detect regressions caused by future code changes.

2018-11-27 10:08 UTC, James-Adam commented on rest-assured/src/test/java/io/restassured/RestAssuredTest.java
> +  @Rule public Timeout globalTimeout = new Timeout(10000);
Timeout and import org.junit.rules.Timeout; can be removed

2018-11-27 11:03 UTC, James-Adam commented on rest-assured/src/test/java/io/restassured/specification/ArgumentTest.java
> +  @Rule public ExpectedException thrown = ExpectedException.none();
We can remove timeout, timeout rules, and expectedexception rule.

2018-11-27 11:05 UTC, James-Adam commented on rest-assured/src/test/java/io/restassured/specification/ArgumentTest.java
> +  @Test
I'd think about removing a hashCode test where possible.

2018-11-27 11:05 UTC, sudo-jaa requested changes
Remove redundant timeout and ExpectedException rules, and hashCode test.

2018-11-28 09:56 UTC, petersear commented on rest-assured/src/test/java/io/restassured/specification/ArgumentTest.java
> +  @Test
Removed

2018-11-28 09:56 UTC, petersear commented on rest-assured/src/test/java/io/restassured/RestAssuredTest.java
> +  @Rule public Timeout globalTimeout = new Timeout(10000);
Thanks. Removed.

2018-11-28 09:56 UTC, petersear commented on rest-assured/src/test/java/io/restassured/specification/ArgumentTest.java
> +  @Rule public ExpectedException thrown = ExpectedException.none();
Removed.

2018-11-28 11:14 UTC, paulkennethkent requested changes

2018-11-28 11:14 UTC, paulkennethkent commented on rest-assured/src/test/java/io/restassured/RestAssuredTest.java
> +  @Test
I don't think this `preemptiveOutputNotNull ` test is meaningful enough to submit

2018-11-28 11:14 UTC, paulkennethkent commented on rest-assured/src/test/java/io/restassured/specification/ArgumentTest.java
> +  public void withArgInputZeroOutputNotNull() {
I don't think this `withArgInputZeroOutputNotNull` test is meaningful enough to submit. If you look at what it's testing something super simple that can't really break?

2018-11-29 10:33 UTC, petersear commented
All comments addressed, new changes pushed.

2018-11-29 10:37 UTC, JohnLBergqvist approved these changes
I presume there was no `true` test-case for that last one?

2018-11-29 10:37 UTC, sudo-jaa approved these changes

2018-11-29 10:40 UTC, petersear commented
Thanks. No, only three tests generated for that class.

2018-11-29 17:43 UTC, closed without merging